# Generated by Django 5.1.3 on 2024-11-09 15:04

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site_settings/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site_settings/')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('facebook', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('meta_description', models.TextField(blank=True, max_length=160)),
                ('meta_keywords', models.TextField(blank=True, max_length=255)),
                ('about_us', ckeditor.fields.RichTextField()),
                ('terms_and_conditions', ckeditor.fields.RichTextField()),
                ('privacy_policy', ckeditor.fields.RichTextField()),
                ('disclaimer', ckeditor.fields.RichTextField()),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('google_analytics_id', models.CharField(blank=True, max_length=50)),
                ('custom_css', models.TextField(blank=True)),
                ('custom_js', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
