# Generated by Django 5.1.3 on 2024-11-10 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_bitcoinwallet_bitcoinpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='bitcoinpayment',
            name='payment_proof',
            field=models.ImageField(upload_to='payment_proofs/'),
        ),
        migrations.AddField(
            model_name='product',
            name='pricing_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracking.pricingplan'),
        ),
    ]
