# Generated by Django 5.1.3 on 2024-11-10 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0006_pricingplan_alter_bitcoinpayment_payment_proof_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingplan',
            name='description',
            field=models.TextField(help_text='Enter features separated by commas'),
        ),
    ]
